:doctype: book
:source-highlighter: rouge
:icons: font
:docinfo1:
:toc: left
[[app.js]]
== App.js

App is the entry point and does little else other than import component
modules, and create an `S` root node. The components and their ordering
create the main display page, which in this Single Page Application is
the whole app (most of which is hidden at this point).

[[modules-and-components]]
=== Modules and Components

Though the app is made of purely modular components, most were isolated
from other code as my development evolved. Eventually, everything became
a module with a purely functional component in it.

With a more complex app, I’d create an `index.js` module that imports
and exports these components, but no need here.

There are more components than these seven. These are the top level
components, out of 15 in all.

All components in my app are ES6 modules, in addition to modules that
are not components, such as objects with text arrays.

=== Source

.App.js
[source,jsx,numbered]
----
import S from 's-js'
import * as Surplus from 'surplus'
import TopNav from './TopNav.js'
import Header from './Header.js'
import Intro from './Intro.js'
import Pictures from './Pictures.js'
import News from './News.js'
import Events from './Events.js'
import Footer from './Footer.js'
/**
   It all starts here. The entry point to the application. Index.html
   will import the bundle that contains this, and provide the document
   body that this appends as a child.

   The top level components are introduced here. Order is important!
 */
let view = S.root(() =>
  <div className='App'>
    <div className='main'>
      <TopNav/>
      <Header/>
      <Intro/>
      <Pictures/>
      <News/>
      <Events/>
      <Footer/>
    </div>
  </div>
)
document.body.appendChild(view)
----

