:doctype: book
:source-highlighter: rouge
:icons: font
:docinfo1:
:toc: left
[[topnav.js]]
== TopNav.js

This is a relatively simple Top Navigation bar, or rather a misnamed
menubar. Since I have other menus in another context I’ll leave the name
as is.

An important aspect of this component is its fixed position placement at
the top of the page as set in `App.css`. The `SideNav` and `ModalBase`
components are children of `TopNav` to take advantage of this fixed
position, even though they are unrelated otherwise, and hidden until
opened.

The background is initially transparent, but when a non-contrasting
background underneath scrolls under it, the text would be obscurred. To
prevent this, a more opaque style is added when the underlying window is
scrolled up more than 30px, and removed when not.

NOTE: The `window.addEventListener` event handler is plain old
JavaScript and DOM. Platforms with virtual DOMs like `React` can’t do
this directly, but `Surplus` doesn’t get in the way.

Menu elements use `onClick` to act as buttons, and either produce
dropdown menus or invoke actions.

`TopNav` takes text for menu names and content from `textStrings`. As in
the “hello world” example, there is an object key with an array of
strings. `langIndex()` selects the text to display. This pattern is
repeated thoughout the app.

The `SideNav` component exports a function that controls its visibility,
called `displayState` which is controlled by the hamburger menu icon. It
opens or toggles this display with `openSide()` and `toggle()`
functions.

Another important toggle is the `li` element that controls
`toggleLang()`, a function imported from `langIndex.js` which also
exports the S data function `langIndex()`. A click on this element
changes all displayed text to another language.

=== Source

.TopNav.js
[source,jsx,numbered]
----
import S from 's-js'
import * as Surplus from 'surplus'
import {textStrings as txt} from './textStrings.js'
import {langIndex, toggleLang} from './langIndex.js'
import Dropdown from './Dropdown.js'
import SideNav from './SideNav.js'
import {displayState} from './SideNav.js'
import ModalBase from './ModalBase.js'
import {displayModal} from './ModalBase.js'

// Give topNav some opacity when scrolled down past 30px.
window.addEventListener('scroll',() => {
  if(window.scrollY > 30) {
    document.getElementsByClassName('topNav')[0].className='topNav opaque'
  } else {
    document.getElementsByClassName('topNav')[0].className='topNav'
  }
})
const openSide = () => { // Opens the SideNav menu, via the hamburger button.
  displayState('block')
}
const toggleSide = () => {
  displayState() == 'block' ? displayState('none') : displayState('block')
}
/** TopNav is fixed at the top of the page, so it acts an an anchor to
   Components that don't scroll with the rest of the page content. So
   it has a dual purpose, the other being to provide dropdown menus,
   as provided by its child component Dropdown with parameters and children.  
 */
export default function TopNav() {
  return (<nav className='topNav'>
    {/* Horizontal menu, starting with the hamburger 'button'. */}
    <ul>
      <span className='menu' onClick={toggleSide}>
        <li className='burger dropbtn' >☰</li>
        <li>{txt.menu[langIndex()]}<Dropdown></Dropdown></li>
      </span>
      <li>
        {/* Dropdown children invoke modals on selection. */}
        <Dropdown name={txt.masstimes[langIndex()]}>
          {/* size is the width of the modal invoked. Mobile displays will
              override this value in Listings.js and MenuItem.js */}
          <content size='50%'>sundaymass</content>  
          <content size='50%'>weekdaymass</content>
        </Dropdown>
      </li>
      <li>
        <Dropdown name={txt.aboutUs[langIndex()]}>
          <content size='60%'>about</content>
          <content size='60%'>aboutLeo</content>
        </Dropdown>
      </li>
      {/* This toggles the entire site's language content. It's always displayed. */}
      <li className='dropbtn' title={txt.toggle[langIndex()]} onClick={toggleLang}>{txt.language[langIndex()]}</li>
    </ul>
    {/* SideNav menubar is hidden until invoked. */}
    <SideNav></SideNav>
    {/* Hidden until invoked. ModalBase is here for display fixed anchor point. */}
    <ModalBase className='modal'></ModalBase> 
  </nav>)
}
----

