exports.str = {
  fund1: ['general fund','fondo general'],
  fund2: ['latin america','America latina'],
  fund3: ['building fund','fondo de construcción'],
  //fund3: ['Maidens','Doncellas'],
  //fund3: ['CCE','CCE'],
  //fund5: ['Hall Rental','Alquiler de Salón'],
  //fund2: ['',''],
  //fund3: ['',''],
  fund4: ['',''],
  fund5: ['',''],
  fund6: ['',''],
  money1: "$6,075.00",
  money2: "$207.76",
  money3: "$80.00",
  money4: "",
  money5: "",
  money6: "",
  sum: "$6,264.76",
  gift: ['your gift to god','Su Regalo de Dios'],
  thanks: ['thank you for your generosity!','¡Gracias por tu generosidad!'],
  next: ['',
         ''],
  total: ['total','total'],
  lang: ['en','es']
}
