exports.str = {
  fund1: ['general fund','fondo general'],
  //fund2: ['building fund','fondo de construcción'],
  fund2: ['christmas offering','christmas offering'],
  //fund3: ['Maidens','Doncellas'],
  fund3: ['Tamales','Tamales'],
  //fund5: ['Hall Rental','Alquiler de Salón'],
  fund4: ['building fund','fondo de construcción'],
  fund5: ['',''],
  fund6: ['',''],
  money1: "$1,141.55",
  money2: "$208.00",
  money3: "$36.00",
  money4: "$25.00",
  //money5: "$100.00",
  //money6: "",
  sum: "$1,410.55",
  gift: ['your gift to god','Su Regalo de Dios'],
  thanks: ['thank you for your generosity!','¡Gracias por tu generosidad!'],
  next: ['',
         ''],
  total: ['total','total'],
  lang: ['en','es']
}
